apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: dronacharya-web-pdb
  namespace: dronacharya
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: dronacharya-web
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: dronacharya-ai-pdb
  namespace: dronacharya
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: dronacharya-ai
