apiVersion: v1
kind: Service
metadata:
  name: learnflow-web
  namespace: learnflow
  labels:
    app: learnflow-web
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: learnflow-web
---
apiVersion: v1
kind: Service
metadata:
  name: learnflow-ai
  namespace: learnflow
  labels:
    app: learnflow-ai
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    app: learnflow-ai
