apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: learnflow-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - dronacharya.app
        - www.dronacharya.app
      secretName: dronacharya-tls-secret
  rules:
    - host: dronacharya.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: staging-learnflow-web
                port:
                  number: 80
    - host: www.dronacharya.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: staging-learnflow-web
                port:
                  number: 80
