apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dronacharya-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - staging.dronacharya.app
        - api-staging.dronacharya.app
      secretName: dronacharya-staging-tls
  rules:
    - host: staging.dronacharya.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: staging-dronacharya-web
                port:
                  number: 80
    - host: api-staging.dronacharya.app
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: staging-dronacharya-web
                port:
                  number: 80
